
/**
 * Copyright (c) 2012-2018
 * All Rights Reserved by APPSYS and its affiliates.
 * You may not use, copy, distribute, modify, transmit in any form this file
 * except in compliance with APPSYS in writing by applicable law.
 *
 */
/**
 * @file    SpecialSignal.h
 * @brief   brief function description.
 * @details detailed function description.
 * @version 1.0
 * @author  wzc
 * @date    2023-08-23
 *
 * Edit History
 * ----------------------------------------------------------------------------
 * DATE                     NAME               DESCRIPTION
 * 2023-08-23               wzc             Create it.
 *
 */

#ifndef SPECIALSIGNAL_H
#define SPECIALSIGNAL_H

typedef enum { 
    E_IVI_USERGEARFB_0X408_INFO,
    E_IVI_LOCKCLOSEWINSET_0X096_INFO,
    E_IVI_CHILDLOCKCTRL_0X075_INFO,
    E_IVI_CENTRALLOCKCTRL_0X075_INFO,
    E_IVI_FUELPORTCAPOPENCTRL_0X075_INFO,
    E_IVI_V2VCHRGONOFFSET_0X075_INFO,
    E_IVI_OBCDSCHRGONOFFSET_0X075_INFO,
    E_IVI_CHRGPORTCAPOPENCTRL_0X075_INFO,
    E_IVI_NORMALHVOFFREQUEST_0X075_INFO,
    E_IVI_MIRRORSW_0X075_INFO,
    E_IVI_REARDEFROSTCTRL_0X075_INFO,
    E_IVI_MAXFUELCONSUMPTIONSW_0X075_INFO,
    E_IVI_MAXFUELCONSUMPTIONMODESW_0X075_INFO,
    E_IVI_APPROACHINGUNLOCKCTRL_0X075_INFO,
    E_IVI_AWAYLOCKCTRL_0X075_INFO,
    E_IVI_NOZZLEHEATINGSW_0X095_INFO,
    E_IVI_RVMIRRORAUTOTURNDOWNSET_0X095_INFO,
    E_IVI_FOLLOWMEHOMESET_0X095_INFO,
    E_IVI_AUTODRYSET_0X095_INFO,
    E_IVI_VEHICLEMODESET_0X0A5_INFO,
    E_IVI_REGENMODESET_0X0A5_INFO,
    E_IVI_CHARGECONTROL_0X0A5_INFO,
    E_IVI_PARKINGCHARGEREQ_0X0A5_INFO,
    E_IVI_TOWMODESET_0X0A5_INFO,
    E_IVI_MAXCHRGSOCSET_0X0A5_INFO,
    E_IVI_PARKINGCHARGEMODESET_0X0A5_INFO,
    E_IVI_CHARGESETVALID_0X0A5_INFO,
    E_IVI_CHARGESTARTTIMEHOUR_0X0A5_INFO,
    E_IVI_CHARGESTARTTIMEMINUTE_0X0A5_INFO,
    E_IVI_CHARGESTARTTIMEVALID_0X0A5_INFO,
    E_IVI_DRIVEMODESET_0X0A5_INFO,
    E_IVI_EPSMODESET_0X065_INFO,
    E_IVI_ESCOFFSW_0X065_INFO,
    E_IVI_HDCONOFFSET_0X065_INFO,
    E_IVI_AEBONOFFSET_0X065_INFO,
    E_IVI_LCABSDONOFFSET_0X065_INFO,
    E_IVI_RCTAONOFFSETRESERVED_0X065_INFO,
    E_IVI_DOWONOFFSET_0X065_INFO,
    E_IVI_HMAONOFFSET_0X065_INFO,
    E_IVI_LANEASSISTFUNCSET_0X065_INFO,
    E_IVI_LASWARNINGMODESELECTION_0X065_INFO,
    E_TRAILERMODEREQ_0X065_INFO,
    E_IVI_RCTBONOFFSET_0X065_INFO,
    E_IVI_ELKONOFFSET_0X065_INFO,
    E_IVI_AVHONOFFSET_0X065_INFO,
    E_IVI_PCWONOFFSET_0X065_INFO,
    E_IVI_TJAFUNCSET_0X065_INFO,
    E_IVI_ESC_EPBBUTTONRELEASE_0X065_INFO,
    E_IVI_STERRINGWHEELHEATSW_0X105_INFO,
    E_IVI_REARSEATBELTVOICEWARNINGSET_0X0C5_INFO,
    E_IVI_HUDONOFFSET_0X0C5_INFO,
    E_IVI_PDCONOFFSET_0X0C5_INFO,
    E_IVI_VSP_SOUNDCONFIGURE_0X0C5_INFO,
    E_IVI_UNLOCKSOUNDSET_0X0C5_INFO,
    E_IVI_ISAONOFFSET_0X0C5_INFO,
    E_IVI_EASYENTRYSET_0X0F5_INFO,
    E_IVI_DRSEATHEATLEVELSET_0X0F5_INFO,
    E_IVI_PASSSEATHEATLEVELSET_0X0F5_INFO,
    E_IVI_DRSEATMASSLEVELSET_0X0F5_INFO,
    E_IVI_PASSSEATMASSLEVELSET_0X0F5_INFO,
    E_IVI_MIRRORAUTOFOLDUNFOLDSET_0X0F5_INFO,
    E_IVI_DRMASSGINTENSET_0X0F5_INFO,
    E_IVI_PSGMASSGINTENSET_0X0F5_INFO,
    E_IC_HUDILLUMILVSET_0X3F2_INFO,
    E_IVI_PASSAIRBSUPPRESSIONSTSET_0X3F8_INFO,
    E_IVI_HVACONOFFREQ_0X3B5_INFO,
    E_IVI_HVACAUTOMODEREQ_0X3B5_INFO,
    E_IVI_ACENERGYSAVINGREQ_0X3B5_INFO,
    E_IVI_HVACMODEREQ_0X3B5_INFO,
    E_IVI_DRIVERTEMPCSET_0X3B5_INFO,
    E_IVI_HVACBLOWLVREQ_0X3B5_INFO,
    E_IVI_PASSENGERTEMPCSET_0X3B5_INFO,
    E_IVI_HVACDUALMODE_0X3B5_INFO,
    E_IVI_ACREQ_0X3B5_INFO,
    E_MAX
}CanSignal_special_e;
#endif